- hosts: localhost
  become: yes
  vars: 
    image: "images"
  tasks:
    - name: Build docker image
      docker_image:
        name: "{{ image }}"
        build:
          path: .       
        tag: "{{ test }}"
        source: build
        state: present  
      register: output
    - name: Show the output
      debug:
        msg: "{{ output }}"  
