
name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd myapp
        python3 manage.py test
    - name: push to sonarcloud   
      uses: GitHubActionsCI-CD/sonarqube-action@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}    
